set SRC_PATH=D:\@SourceCode\temp\cf 

echo scan package sample.test-runner start... ...
cd %SRC_PATH%\sample.test-runner
call mvn sonar:sonar
echo scan package sample.test-runner done... ...

echo scan package sample.domain start... ...
cd %SRC_PATH%\sample.domain
call mvn sonar:sonar
echo scan package sample.domain done... ...

echo scan package sample.infrastructure start... ...
cd %SRC_PATH%\sample.infrastructure
call mvn sonar:sonar
echo scan package sample.infrastructure done... ...

echo scan package coral-reef start... ...
cd %SRC_PATH%\coral-reef
call mvn sonar:sonar
echo scan package coral-reef done... ...

